const PREFIX = 'LAYOUT_';

export const CHANGENAV = `${PREFIX}CHANGENAV`;
export const COLLAPSESIDEBAR = `${PREFIX}COLLAPSESIDEBAR`;
export const GET_AUTH_POINTS = `${PREFIX}GET_AUTH_POINTS`;
export const COMMON_OPERATE = `${PREFIX}COMMON_OPERATE`;
